services:
  velocity:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: velocity-proxy
    ports:
      - "25577:25577" # Map to your MC server's port. 
    #environment: # No need to specify if you want to keep the defaults in the Dockerfile 
      #JAVA_MEMORY: "512M"
      #JAVA_FLAGS: "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
    volumes:
      - ./data:/data
    restart: unless-stopped
